# Generated by Django 3.1.6 on 2021-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteURL', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('websiteName', models.CharField(max_length=32)),
            ],
        ),
    ]
